name: Python application test with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v6.0.2
      
    - name: Set up Python 3.10.20
      uses: actions/setup-python@v6
      with:
        python-version: "3.10.20"
        
    - name: Install dependencies
      run: make install
      
    - name: Lint with pylint
      run: make lint
      
    - name: Test with pytest
      run: make test
